### PR TITLE
Added support for scala 2.12.x versions

### PR DESCRIPTION
**Pull request by jeduardocosta**
- Added support for scala 2.12.x versions
- Updated scala 2.11.x version to 2.11.11
- Updated sbt libraries to last version
- Bump library version from 0.2.1 to 0.2.2

http://www.scala-sbt.org/0.13/docs/Cross-Build.html

### CODE REVIEW

**Comment by jeduardocosta** [comment]
It's necessary to update the library version? Or we can use the 0.2.1 version?

**Comment by Unisay** [comment]
Thanks

**Comment by Unisay** [comment]
I have just released 0.3.0

**Comment by jeduardocosta** [comment]
Sure, no problem. Thanks.

**Pull request merged**
